### PR TITLE
Translated to Polish

### PR DESCRIPTION
**Pull request by Zwirzu**
Polish translation.

### CODE REVIEW

**Comment by Zwirzu** [comment]
I signed It.

14 wrz 2017 01:09 "googlebot" <notifications@github.com> napisał(a):

**Comment by dsaff** [comment]
Hi!

Do you know if this will be displayed by default by GitHub in the appropriate locale, or will Polish readers have to know to look for it in the repo?  Thanks!

   David

**Comment by Zwirzu** [comment]
They have to look into repo
Zwirzu

**Comment by dsaff** [comment]
Thanks!

**Pull request merged**
